
language: java
jdk: 
 - openjdk8
addons:
   sonarcloud:
     organization: "muradexpert"
     token:
       secure: "475906dbfcbc9913b73d833d20c3476e7598150c" # encrypted value of your token

script:
 # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
before_install:
 - chmod +x mvnw
